source:      .
destination: ./_site

future:      true
lsi:         false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

title:       Pel mon en moto
description: Viatge des de Barcelona a Australia en moto
author:      Paula & Tia
email:       pelmonenmoto@gmail.com

exclude:     [_site]

collections:
  stages_en:
    output: true
    permalink: /en/diary/stages/:title
  stages_es:
    output: true
    permalink: /es/diary/stages/:title
  blog_entries_en:
    output: true
    permalink: /en/blog/entries/:title
  blog_entries_es:
    output: true
    permalink: /es/blog/entries/:title
